window.App=window.App||{};
(function(){
 const el=App.ui.el;
 function crud(cfg){
  let state={q:"",page:1,pageSize:8};
  const getCell=(r,c)=>c.resolve?c.resolve(r):(c.format?c.format(r[c.key],r):(r[c.key]==null?"":String(r[c.key])));
  const rows=()=>{let a=App.db.all(cfg.coll);a.sort(cfg.ordenar||((x,y)=>(y.id||0)-(x.id||0)));const q=state.q.trim().toLowerCase();if(q)a=a.filter(r=>(cfg.buscaKeys||[]).concat(cfg.colunas.map(c=>c.key)).some(k=>String(r[k]??getCell(r,{key:k})).toLowerCase().includes(q)));return a;};
  function form(rec,paint){const vals=rec?{...rec}:{};const campos=(cfg.campos||[]).map(c=>({...c,required:!!c.required || (!rec && !!c.requiredOnCreate),validate:c.validate?((v)=>c.validate(v,rec)):undefined,skipValidationIfEmpty:!!rec&&c.type==="password"}));if(rec)campos.forEach(c=>{if(c.type==="password")vals[c.key]="";});App.ui.modalForm({titulo:(rec?"Editar ":"Novo ")+cfg.singular,campos,valores:vals}).then(res=>{if(!res)return;const d={};campos.forEach(c=>{let v=res[c.key];if(c.type==="password"&&rec&&!String(v).trim()){return;}if(c.type==="number")v=v===""?0:Number(v);else if(c.optionsFrom)v=v===""?null:Number(v);if(c.transform)v=c.transform(v);d[c.key]=v;});const saved=rec?App.db.update(cfg.coll,rec.id,d):App.db.insert(cfg.coll,d);if(!saved){App.ui.toast("Não foi possível salvar o registro.","error");return;}App.db.insert("logs",{usuario:App.auth.atual()?.nome||"-",acao:`${rec?"editar":"criar"} ${cfg.singular}`,data_hora:new Date().toISOString()});cfg.aoSalvar?.(saved,rec?"editar":"criar");App.ui.toast(rec?"Alterações salvas.":`${cfg.singular} cadastrado com sucesso.` ,"ok");paint();});}
  function remove(r,paint){App.ui.confirmar(`Excluir “${r[cfg.rotulo||"nome"]||"#"+r.id}”?`,"Excluir").then(ok=>{if(!ok)return;try{cfg.antesDeExcluir?.(r.id);const removed=App.db.remove(cfg.coll,r.id);if(!removed){App.ui.toast("Não foi possível excluir o registro.","error");return;}App.ui.toast("Registro excluído.","ok");paint();}catch(e){App.ui.toast(e.message,"error");}});}
  function exportCsv(){const a=rows();const header=cfg.colunas.map(c=>c.label);const body=a.map(r=>cfg.colunas.map(c=>String(getCell(r,c)).replace(/"/g,'""')));const csv="\uFEFF"+[header,...body].map(x=>x.map(v=>`"${v}"`).join(";")).join("\r\n");App.ui.baixar(`${cfg.coll}.csv`,csv,"text/csv;charset=utf-8");}
  function render(container){App.ui.clear(container);const title=el("div",{class:"page-head"},[el("div",{},[el("span",{class:"eyebrow"},cfg.grupo||"GESTÃO"),el("h1",{},cfg.titulo),el("p",{},cfg.descricao||"Controle e acompanhamento.")]),el("div",{class:"page-actions"},[App.ui.button("Exportar",exportCsv,{variant:"secondary",icon:"download"}),cfg.somenteLeitura?null:App.ui.button(`Novo ${cfg.singular}`,()=>form(null,paint),{icon:"plus"})])]);container.append(title);const summary=el("div",{class:"summary-grid"});const controls=el("div",{class:"filter-bar"});const search=el("input",{class:"filter-input",type:"search",placeholder:`Buscar ${cfg.singular.toLowerCase()}...`,oninput:e=>{state.q=e.target.value;state.page=1;paint();}});controls.append(el("div",{class:"search-wrap"},[App.ui.icon("search"),search]));const tableBox=el("div",{class:"table-card"});container.append(summary,controls,tableBox);
   function paint(){const all=rows();App.ui.clear(summary);if(cfg.resumo){const s=cfg.resumo(all);summary.append(...(Array.isArray(s)?s:[s]));}App.ui.clear(tableBox);const start=(state.page-1)*state.pageSize;const page=all.slice(start,start+state.pageSize);if(!page.length){tableBox.append(el("div",{class:"empty-state"},[el("div",{class:"empty-icon"},App.ui.icon("search")),el("strong",{},"Nenhum registro encontrado"),el("span",{},state.q?"Tente outra busca.":"Comece cadastrando um novo registro.")]));return;}
     const table=el("table",{});const th=cfg.colunas.map(c=>el("th",{},c.label));if(!cfg.somenteLeitura)th.push(el("th",{class:"actions-col"},"Ações"));table.append(el("thead",{},el("tr",{},th)));const tbody=el("tbody");page.forEach(r=>{const cells=cfg.colunas.map(c=>{const val=getCell(r,c);return el("td",{},c.tag?el("span",{class:`status-pill ${c.tag(r)}`},val):val);});if(!cfg.somenteLeitura)cells.push(el("td",{class:"actions-col"},[App.ui.iconButton("eye","Visualizar",()=>{if(cfg.onView)cfg.onView(r);else form(r,paint);}),App.ui.iconButton("edit","Editar",()=>form(r,paint)),App.ui.iconButton("trash","Excluir",()=>remove(r,paint),"danger") ]));tbody.append(el("tr",{},cells));});table.append(tbody);tableBox.append(el("div",{class:"table-scroll"},table));const total=Math.max(1,Math.ceil(all.length/state.pageSize));if(state.page>total){state.page=total;paint();return;}if(total>1)tableBox.append(el("div",{class:"pagination"},[App.ui.button("Anterior",()=>{if(state.page>1){state.page--;paint();}},{variant:"secondary",small:true}),el("span",{},`Página ${state.page} de ${total}`),App.ui.button("Próxima",()=>{if(state.page<total){state.page++;paint();}},{variant:"secondary",small:true})]));}
   paint();}
  return {render};
 }
 App.crud=crud;
})();
